import { ArrowLeft, CheckCircle2, ChevronRight, ClipboardCheck, EyeOff, FileInput, Inbox, LoaderCircle, Plus, Save, ShieldCheck, Star, UsersRound, X } from "lucide-react";
import { type FormEvent, useEffect, useState } from "react";
import { useParams } from "react-router-dom";

type User = { id: string; email: string; name: string };
type EventRecord = { id: string; organizationName: string; name: string; status: string };
type Round = { id: string; name: string; position: number; isBlind: boolean; opensAt: string | null; closesAt: string | null; status: string; assignmentCount: number; completedCount: number; reviewerCount: number; averageScore: number | null };
type ScoreField = { id: string; roundId: string; label: string; fieldType: "numeric" | "select" | "text"; options?: { label: string; value: number }[]; minValue: number | null; maxValue: number | null; weight: number; required: boolean; position: number };
type Reviewer = { id: string; name: string; email: string; assignmentCount: number; completedCount: number };
type Submission = { id: string; title: string; submitterName: string; status: string };
type Assignment = { id: string; submissionId: string; title: string; abstract: string; roundId: string; roundName: string; isBlind: boolean; closesAt: string | null; roundStatus: string; completedAt: string | null; weightedScore: number | null; recommendation: string | null };
type AssignmentDetail = Assignment & { answers: Record<string, unknown>; reviewAnswers: Record<string, unknown>; recommendation: string | null; comment: string | null; reviewSubmittedAt: string | null };
type FormField = { fieldKey: string; label: string; section: string };
type Person = { name: string; email: string; role: string; organization: string | null };

async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, { credentials: "same-origin", ...init, headers: { "content-type": "application/json", ...init?.headers } }); const result = await response.json() as T & { error?: { message?: string; fields?: Record<string, string> } }; if (!response.ok) { const error = new Error(result.error?.message ?? "The request could not be completed.") as Error & { fields?: Record<string, string> }; error.fields = result.error?.fields; throw error; } return result; }

function EventChrome({ event, user, eventId, children, active }: { event?: EventRecord; user: User; eventId: string; children: React.ReactNode; active: "reviews" }) {
  return <div className="event-workspace"><aside className="event-sidebar"><a className="wordmark" href="/"><span aria-hidden="true" className="mark">PL</span>ProgramLoom</a><a className="back-link" href="/app"><ArrowLeft size={15} /> All events</a><div className="event-identity"><small>{event?.organizationName}</small><strong>{event?.name}</strong><span>{event?.status}</span></div><nav className="event-nav" aria-label="Event workspace"><a href={`/app/events/${eventId}`}><FileInput size={18} /> Call for proposals</a><a href={`/app/events/${eventId}/submissions`}><Inbox size={18} /> Submissions</a><a className={active === "reviews" ? "active" : ""} href={`/app/events/${eventId}/reviews`}><ClipboardCheck size={18} /> Reviews</a><span><UsersRound size={18} /> Speakers</span><span><CheckCircle2 size={18} /> Agenda</span></nav><div className="sidebar-user"><span>{user.name}</span><small>{user.email}</small></div></aside>{children}</div>;
}

export function EventReviews({ user }: { user: User }) {
  const { eventId = "" } = useParams(); const [event, setEvent] = useState<EventRecord>(); const [role, setRole] = useState<string>(); const [loading, setLoading] = useState(true); const [feedback, setFeedback] = useState<{ kind: "error" | "success"; message: string }>();
  useEffect(() => { api<{ event: EventRecord; role: string }>(`/api/events/${eventId}`).then((result) => { setEvent(result.event); setRole(result.role); }).catch((error: Error) => setFeedback({ kind: "error", message: error.message })).finally(() => setLoading(false)); }, [eventId]);
  if (loading) return <main className="loading-page" aria-busy="true"><LoaderCircle className="spin" /> Loading reviews…</main>;
  return <EventChrome event={event} user={user} eventId={eventId} active="reviews"><main id="main-content" className="event-main reviews-main">{feedback && <div className={`form-status form-status-${feedback.kind}`}>{feedback.message}</div>}{role === "reviewer" ? <ReviewerQueue eventId={eventId} /> : <OrganizerReviews eventId={eventId} />}</main></EventChrome>;
}

function OrganizerReviews({ eventId }: { eventId: string }) {
  const [rounds, setRounds] = useState<Round[]>([]); const [scorecards, setScorecards] = useState<ScoreField[]>([]); const [reviewers, setReviewers] = useState<Reviewer[]>([]); const [submissions, setSubmissions] = useState<Submission[]>([]); const [selectedRoundId, setSelectedRoundId] = useState<string>(); const [selectedSubmissions, setSelectedSubmissions] = useState<string[]>([]); const [selectedReviewers, setSelectedReviewers] = useState<string[]>([]); const [feedback, setFeedback] = useState<{ kind: "error" | "success"; message: string }>(); const [busy, setBusy] = useState(false);
  const selected = rounds.find((round) => round.id === selectedRoundId);
  async function load(preferred?: string) { const [config, intake] = await Promise.all([api<{ rounds: Round[]; scorecards: ScoreField[]; reviewers: Reviewer[] }>(`/api/reviews/events/${eventId}`), api<{ submissions: Submission[] }>(`/api/events/${eventId}/submissions?status=pending`)]); setRounds(config.rounds); setScorecards(config.scorecards); setReviewers(config.reviewers); setSubmissions(intake.submissions); setSelectedRoundId(preferred ?? selectedRoundId ?? config.rounds[0]?.id); }
  useEffect(() => { load().catch((error: Error) => setFeedback({ kind: "error", message: error.message })); }, [eventId]);
  async function createRound(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const data = new FormData(event.currentTarget); try { const result = await api<{ round: Round }>(`/api/reviews/events/${eventId}/rounds`, { method: "POST", body: JSON.stringify({ name: data.get("name"), isBlind: data.get("isBlind") === "on" }) }); event.currentTarget.reset(); await load(result.round.id); setFeedback({ kind: "success", message: "Review round created. Add its scorecard next." }); } catch (error) { setFeedback({ kind: "error", message: error instanceof Error ? error.message : "Could not create the round." }); } finally { setBusy(false); } }
  async function addField(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; setBusy(true); const data = new FormData(event.currentTarget); const type = String(data.get("fieldType")); const options = String(data.get("options") ?? "").split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const [label, rawScore] = line.split("|"); return { label: label.trim(), value: Number(rawScore) }; }); try { await api(`/api/reviews/events/${eventId}/rounds/${selected.id}/fields`, { method: "POST", body: JSON.stringify({ label: data.get("label"), fieldType: type, minValue: type === "numeric" ? Number(data.get("minValue")) : undefined, maxValue: type === "numeric" ? Number(data.get("maxValue")) : undefined, options: type === "select" ? options : undefined, weight: Number(data.get("weight") || 1), required: data.get("required") === "on" }) }); event.currentTarget.reset(); await load(selected.id); setFeedback({ kind: "success", message: "Scorecard field added." }); } catch (error) { setFeedback({ kind: "error", message: error instanceof Error ? error.message : "Could not add the score field." }); } finally { setBusy(false); } }
  async function setRoundStatus(status: string) { if (!selected) return; setBusy(true); try { await api(`/api/reviews/events/${eventId}/rounds/${selected.id}`, { method: "PATCH", body: JSON.stringify({ status }) }); await load(selected.id); setFeedback({ kind: "success", message: status === "open" ? "Round opened. Assigned reviewers can now score." : `Round ${status}.` }); } catch (error) { setFeedback({ kind: "error", message: error instanceof Error ? error.message : "Could not update the round." }); } finally { setBusy(false); } }
  async function assign() { if (!selected || !selectedSubmissions.length || !selectedReviewers.length) return; setBusy(true); try { const result = await api<{ created: number; conflicts: { reason: string }[] }>(`/api/reviews/events/${eventId}/assignments`, { method: "POST", body: JSON.stringify({ roundId: selected.id, submissionIds: selectedSubmissions, reviewerUserIds: selectedReviewers }) }); await load(selected.id); setFeedback({ kind: result.conflicts.length ? "error" : "success", message: `${result.created} assignments prepared.${result.conflicts.length ? ` ${result.conflicts.length} speaker/reviewer conflicts were safely skipped.` : ""}` }); } catch (error) { setFeedback({ kind: "error", message: error instanceof Error ? error.message : "Could not create assignments." }); } finally { setBusy(false); } }
  return <><header className="event-heading"><div><p className="kicker">Evaluation workspace</p><h1>Review rounds</h1><p>Shape scorecards, isolate reviewer access, and track every assigned evaluation.</p></div>{selected && <div className="round-actions"><button className="button button-ghost button-small" onClick={() => setRoundStatus(selected.status === "open" ? "closed" : "open")} disabled={busy}>{selected.status === "open" ? "Close round" : "Open round"}</button></div>}</header>{feedback && <div className={`form-status form-status-${feedback.kind}`}>{feedback.message}</div>}
    <div className="review-admin-layout"><aside className="round-list"><div className="panel-title"><div><h2>Rounds</h2><span>{rounds.length}</span></div></div>{rounds.map((round) => <button className={round.id === selectedRoundId ? "selected" : ""} onClick={() => setSelectedRoundId(round.id)} key={round.id}><span><strong>{round.name}</strong><small>{round.status} · {round.completedCount}/{round.assignmentCount} complete</small></span><ChevronRight size={15} /></button>)}<form onSubmit={createRound}><label>New round<input name="name" placeholder="Round 1: Program fit" required /></label><label className="check-row"><input name="isBlind" type="checkbox" /><span><strong>Blind review</strong><small>Hide speaker identity and speaker-section answers.</small></span></label><button className="button button-small" disabled={busy}><Plus size={15} /> Create round</button></form></aside>
      <section className="review-config">{!selected ? <div className="builder-empty"><Star size={34} /><h2>Create a review round</h2><p>Rounds keep scorecards, assignments, and deadlines independent.</p></div> : <><div className="review-round-heading"><div><span className={`status-dot ${selected.status === "open" ? "live" : ""}`} />{selected.status}<h2>{selected.name}</h2>{selected.isBlind && <em><EyeOff size={13} /> Blind</em>}</div><div><strong>{selected.averageScore ?? "—"}</strong><small>Average score</small></div></div><div className="review-stats"><div><strong>{selected.assignmentCount}</strong><span>Assignments</span></div><div><strong>{selected.completedCount}</strong><span>Completed</span></div><div><strong>{selected.reviewerCount}</strong><span>Reviewers</span></div></div>
        <section className="scorecard-section"><div><h3>Scorecard</h3><p>Weights combine numeric and scored-select answers into one aggregate.</p></div><div className="scorecard-list">{scorecards.filter((field) => field.roundId === selected.id).map((field) => <div key={field.id}><Star size={15} /><span><strong>{field.label}</strong><small>{field.fieldType} · weight {field.weight}{field.required ? " · required" : ""}</small></span></div>)}</div><form className="score-field-form" onSubmit={addField}><label>Criterion<input name="label" placeholder="Audience value" required /></label><label>Type<select name="fieldType" defaultValue="numeric"><option value="numeric">Numeric</option><option value="select">Scored select</option><option value="text">Reviewer note</option></select></label><label>Minimum<input name="minValue" type="number" defaultValue="1" /></label><label>Maximum<input name="maxValue" type="number" defaultValue="5" /></label><label>Weight<input name="weight" type="number" min="0.1" step="0.1" defaultValue="1" /></label><label className="wide">Select options <small>One per line as Label|Score</small><textarea name="options" rows={3} placeholder={'Strong yes|5\nMaybe|3\nNo|1'} /></label><label className="check-row wide"><input name="required" type="checkbox" defaultChecked /><span><strong>Required</strong><small>Final review cannot submit without this answer.</small></span></label><button className="button wide" disabled={busy}><Plus size={15} /> Add criterion</button></form></section>
        <section className="assignment-section"><div><h3>Assignments</h3><p>Choose submissions and invited reviewers. Speaker/self conflicts are skipped automatically.</p></div>{reviewers.length ? <div className="assignment-columns"><div><h4>Submissions</h4>{submissions.map((submission) => <label className="assignment-choice" key={submission.id}><input type="checkbox" checked={selectedSubmissions.includes(submission.id)} onChange={(event) => setSelectedSubmissions((current) => event.target.checked ? [...current, submission.id] : current.filter((id) => id !== submission.id))} /><span><strong>{submission.title}</strong><small>{submission.submitterName}</small></span></label>)}</div><div><h4>Reviewers</h4>{reviewers.map((reviewer) => <label className="assignment-choice" key={reviewer.id}><input type="checkbox" checked={selectedReviewers.includes(reviewer.id)} onChange={(event) => setSelectedReviewers((current) => event.target.checked ? [...current, reviewer.id] : current.filter((id) => id !== reviewer.id))} /><span><strong>{reviewer.name}</strong><small>{reviewer.completedCount}/{reviewer.assignmentCount} complete</small></span></label>)}</div></div> : <div className="inline-empty"><UsersRound size={24} /><span>Invite reviewers from the Team page before assigning proposals.</span></div>}<button className="button" onClick={assign} disabled={busy || !selectedSubmissions.length || !selectedReviewers.length}>Create assignments</button></section>
      </>}</section></div></>;
}

function ReviewerQueue({ eventId }: { eventId: string }) {
  const [assignments, setAssignments] = useState<Assignment[]>([]); const [selected, setSelected] = useState<AssignmentDetail>(); const [fields, setFields] = useState<FormField[]>([]); const [people, setPeople] = useState<Person[]>([]); const [scorecard, setScorecard] = useState<ScoreField[]>([]); const [answers, setAnswers] = useState<Record<string, unknown>>({}); const [feedback, setFeedback] = useState<{ kind: "error" | "success"; message: string }>(); const [busy, setBusy] = useState(false); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});
  async function load() { const result = await api<{ assignments: Assignment[] }>(`/api/reviews/me/assignments?eventId=${eventId}`); setAssignments(result.assignments); }
  useEffect(() => { load().catch((error: Error) => setFeedback({ kind: "error", message: error.message })); }, [eventId]);
  async function open(id: string) { setBusy(true); try { const result = await api<{ assignment: AssignmentDetail; fields: FormField[]; people: Person[]; scorecard: ScoreField[] }>(`/api/reviews/me/assignments/${id}`); setSelected(result.assignment); setFields(result.fields); setPeople(result.people); setScorecard(result.scorecard); setAnswers(result.assignment.reviewAnswers); } catch (error) { setFeedback({ kind: "error", message: error instanceof Error ? error.message : "Could not open the assignment." }); } finally { setBusy(false); } }
  async function saveReview(event: FormEvent<HTMLFormElement>, submit: boolean) { event.preventDefault(); if (!selected) return; setBusy(true); setFieldErrors({}); const data = new FormData(event.currentTarget); try { const result = await api<{ review: { weightedScore: number | null } }>(`/api/reviews/me/assignments/${selected.id}/review`, { method: "POST", body: JSON.stringify({ answers, recommendation: data.get("recommendation"), comment: data.get("comment"), submit }) }); setSelected({ ...selected, weightedScore: result.review.weightedScore, reviewSubmittedAt: submit ? new Date().toISOString() : null }); await load(); setFeedback({ kind: "success", message: submit ? "Review submitted." : "Review draft saved." }); } catch (error) { const typed = error as Error & { fields?: Record<string, string> }; setFieldErrors(typed.fields ?? {}); setFeedback({ kind: "error", message: typed.message }); } finally { setBusy(false); } }
  async function recuse() { if (!selected) return; const reason = window.prompt("Why are you unable to review this proposal?"); if (!reason) return; try { await api(`/api/reviews/me/assignments/${selected.id}/recuse`, { method: "POST", body: JSON.stringify({ reason }) }); setSelected(undefined); await load(); setFeedback({ kind: "success", message: "You were recused. The organizer can reassign the proposal." }); } catch (error) { setFeedback({ kind: "error", message: error instanceof Error ? error.message : "Could not recuse." }); } }
  function scoreInput(field: ScoreField) { const value = answers[field.id]; if (field.fieldType === "text") return <textarea rows={4} value={String(value ?? "")} onChange={(event) => setAnswers((current) => ({ ...current, [field.id]: event.target.value }))} />; if (field.fieldType === "select") return <select value={String(value ?? "")} onChange={(event) => setAnswers((current) => ({ ...current, [field.id]: event.target.value }))}><option value="">Choose…</option>{field.options?.map((option) => <option key={option.label}>{option.label}</option>)}</select>; return <input type="number" min={field.minValue ?? undefined} max={field.maxValue ?? undefined} step="0.1" value={String(value ?? "")} onChange={(event) => setAnswers((current) => ({ ...current, [field.id]: event.target.value === "" ? "" : Number(event.target.value) }))} />; }
  return <><header className="event-heading"><div><p className="kicker">Reviewer workspace</p><h1>Your review queue</h1><p>Only proposals explicitly assigned to you appear here.</p></div><div className="submission-total"><strong>{assignments.filter((item) => item.completedAt).length}/{assignments.length}</strong><span>Complete</span></div></header>{feedback && <div className={`form-status form-status-${feedback.kind}`}>{feedback.message}</div>}<section className="reviewer-list">{assignments.length ? assignments.map((assignment) => <button onClick={() => open(assignment.id)} key={assignment.id}><span className={assignment.completedAt ? "review-complete" : "review-pending"}>{assignment.completedAt ? <CheckCircle2 size={16} /> : <Star size={16} />}</span><span><small>{assignment.roundName}{assignment.isBlind ? " · Blind" : ""}</small><strong>{assignment.title}</strong><p>{assignment.abstract}</p></span><span><strong>{assignment.weightedScore ?? "—"}</strong><small>Score</small></span><ChevronRight size={17} /></button>) : <div className="submission-empty"><ShieldCheck size={32} /><h2>Your queue is clear</h2><p>Assigned proposals will appear here when a review round opens.</p></div>}</section>
    {selected && <div className="detail-backdrop"><aside className="review-detail"><header><div><small>{selected.roundName}{selected.isBlind ? " · Blind review" : ""}</small><h2>{selected.title}</h2></div><button className="plain-icon" onClick={() => setSelected(undefined)}><X size={19} /></button></header><div className="review-proposal">{!selected.isBlind && people.map((person) => <div className="review-person" key={person.email}><strong>{person.name}</strong><span>{person.organization || person.email}</span></div>)}{fields.map((field) => <section key={field.fieldKey}><small>{field.label}</small><div>{String(selected.answers[field.fieldKey] ?? "—")}</div></section>)}</div><form className="review-scorecard" onSubmit={(event) => saveReview(event, ((event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null)?.value !== "draft")}><h3>Scorecard</h3>{scorecard.map((field) => <label key={field.id}>{field.label}{field.required && <em>Required</em>}<small>Weight {field.weight}</small>{scoreInput(field)}{fieldErrors[field.id] && <span className="field-error">{fieldErrors[field.id]}</span>}</label>)}<label>Recommendation<select name="recommendation" defaultValue={selected.recommendation ?? "maybe"}><option value="approve">Approve</option><option value="maybe">Maybe</option><option value="deny">Deny</option></select></label><label>Reviewer comment<textarea name="comment" rows={5} defaultValue={selected.comment ?? ""} /></label><div className="review-actions"><button className="button button-ghost" value="draft" disabled={busy}><Save size={15} /> Save draft</button><button className="button" value="submit" disabled={busy}><CheckCircle2 size={15} /> Submit review</button></div><button type="button" className="recuse-link" onClick={recuse}>Declare a conflict or recuse myself</button></form></aside></div>}
  </>;
}
